DROP DATABASE IF EXISTS "THEATRE_DB";
CREATE DATABASE "THEATRE_DB";

CREATE TABLE User(
    Email VARCHAR(254) NOT NULL,
    Pwd VARCHAR(25) NOT NULL,
    PRIMARY KEY(Email)
);

CREATE TABLE RegisteredUser(
    Email VARCHAR(254) NOT NULL,
    Pwd VARCHAR(25) NOT NULL,
    PRIMARY KEY(Email)
    FOREIGN KEY(Email) REFERENCES User(Email)
);
